#!/usr/bin/env zsh

function zgenom-update() {
    setopt localoptions extended_glob nullglob
    for repo in $ZGEN_DIR/**/*/.git/; do
        repo="${repo%/.git/}"
        __zgenom_err "Updating '${repo#$ZGEN_DIR/}' ..."
        (cd "${repo}" \
            && -zgen-git-pull \
            && git submodule update --recursive)
        __zgenom_out ''
    done

    zgenom-reset
    date +%s >! "$ZGEN_DIR/.zgenom-plugin-lastupdate"
}

zgenom-update $@
