#!/usr/bin/env zsh

function zgenom-pmodule() {
    local repo="${1}"
    local branch="${2}"

    local dir="$(__zgenom_clone_dir ${repo} --branch ${branch})"

    zgenom-clone "${repo}" "${branch}"

    local module="${repo:t}"
    __zgenom_prezto_load "'${module}'"
}

zgenom-pmodule $@
