#!/usr/bin/env zsh

function zgenom-selfupdate() {
    if [[ -e "${ZGEN_SOURCE}/.git" ]]; then
        (cd "${ZGEN_SOURCE}" \
            && git pull) \
            && zgenom-reset \
            && date +%s >! "$ZGEN_DIR/.zgenom-system-lastupdate"
    else
        __zgenom_err "Not running from a git repository; cannot automatically update."
        return 1
    fi
}

zgenom-selfupdate $@
