#!/usr/bin/env zsh

if ! typeset -f compdef >/dev/null; then
    _ZGENOM_COMPDEFS=()
    function compdef() {
        _ZGENOM_COMPDEFS+=("$*")
    }

    function __zgenom_compdef() {
        local comp
        for comp in $_ZGENOM_COMPDEFS; do eval "compdef $comp"; done
        unset _ZGENOM_COMPDEFS
    }
else
    function __zgenom_compdef() {}
fi

# Ensure running once
function zgenom-compdef() {}
