#!/usr/bin/env zsh

function zgenom-oh-my-zsh() {
    if [[ -z $ZSH ]]; then
        ZSH="$(___zgenom_clone_dir "$ZGEN_OH_MY_ZSH_REPO" "$ZGEN_OH_MY_ZSH_BRANCH")"
    fi

    local file="${1:-oh-my-zsh.sh}"
    zgenom-load "$ZGEN_OH_MY_ZSH_REPO" "${file}" "$ZGEN_OH_MY_ZSH_BRANCH"
}

zgenom-oh-my-zsh $@
